spring.datasource.url=jdbc:sqlite:./treasure_game.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=8080

jwt.secret=qb1D0aht1BMWZcManC9iaxDOC0nl5v9D8agW1vWg2qmEKMgErx7B5UXRtuJY29NY
jwt.expiration=86400000
