spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlite:./treasure_game.db}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.sqlite.JDBC}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.community.dialect.SQLiteDialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=${PORT:8080}

jwt.secret=${JWT_SECRET:qb1D0aht1BMWZcManC9iaxDOC0nl5v9D8agW1vWg2qmEKMgErx7B5UXRtuJY29NY}
jwt.expiration=86400000

allowed.origins=${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001,http://localhost:5173}
